# Welcome to Jekyll!
#
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arnegockeln.com" # the base hostname & protocol for your site, e.g. http://example.com
default_title: "Software Entwicklung & Beratung"
default_description: "Diese Webseite ist über Arne Gockeln, ein Senior Softwareentwickler und Software Berater."
head_title: "AG"
head_desc: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# plugin  jekyll-paginate-v2 configuration
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  title: ''
  permalink: '/blog/:num/'
  sort_field: 'date'
  sort_reverse: true
  limit: 0
  trail:
    before: 1
    after: 1

# defaults to /:categories/:year/:month/:title:output_ext
permalink: /blog/:year/:month/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _template
  - _temp
  - .sass-cache
  - package.json
  - .gitignore
  - arnegockeln.sublime-workspace
  - arnegockeln.sublime-project
  - README.md
  - vendor
  - _theme

jekyll-minifier:
  remove_comments: true
  compress_css: true
  compress_javascript: true
  exclude: ["*.html", "*.xml"]

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      bodycss: single
      header: small
  -
    scope:
      path: ""
      type: pages
    values:
      is_post: false
