# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arnegockeln.com" # the base hostname & protocol for your site, e.g. http://example.com
default_title: "Algorithmic Adventurer"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false

# plugin  jekyll-paginate-v2 configuration
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  title: ''
  permalink: '/blog/:num/'
  sort_field: 'date'
  sort_reverse: true
  limit: 0
  trail:
    before: 1
    after: 1

# defaults to /:categories/:year/:month/:title:output_ext
permalink: /:year/:month/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _template
  - .sass-cache
  - package.json
  - .gitignore
  - arnegockeln.sublime-workspace
  - arnegockeln.sublime-project
  - README.md
#  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll-minifier:
  remove_comments: true
  compress_css: true
  compress_javascript: true
  exclude: ["*.html", "*.xml"]

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts