menu:
- name: 'Start'
  url: '/index.html'
- name: 'Software'
  sub:
    - name: 'Entwicklung'
      url: '/softwareentwicklung.html'
#    - name: 'Schulung'
#      url: '/softwareschulung.html'
    - name: 'Artikel'
      url: '/blog/softwaredev'
- name: 'Trading'
  sub:
    - name: 'Schulung'
      url: '/priceactiontrading.html'
    - name: 'Artikel'
      url: '/blog/trading'
- name: 'Blog'
  sub:
    - name: 'Business'
      url: '/blog/business'
    - name: 'Trading'
      url: '/blog/trading'
    - name: 'Softwareentwicklung'
      url: '/blog/softwaredev'
- name: 'Profil'
  url: '/profil.html'
- name: 'Kontakt'
  url: '/kontakt.html'

footer:
- name: 'Kontakt'
  url: '/kontakt.html'
- name: 'Datenschutz'
  url: '/datenschutz.html'
- name: 'Impressum'
  url: '/impressum.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube', url: 'https://www.youtube.com/channel/UCSP7m2ZTRWOc56kq1gRg7mQ'}
- {icon: 'twitter', url: 'https://twitter.com/arnegockeln'}
- {icon: 'linkedin', url: 'http://www.linkedin.com/in/arnegockeln/'}
- {icon: 'xing', url: 'https://www.xing.com/profile/Arne_Gockeln'}
- {icon: 'github', url: 'https://www.github.com/arnegockeln'}
- {icon: 'rss-square', url: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Sharing is caring!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
