menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/arnegockeln'}
- {icon: 'twitter', link: 'https://twitter.com/arnegockeln'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/arnegockeln/'}
- {icon: 'xing', link: 'https://www.xing.com/profile/Arne_Gockeln'}
- {icon: 'envelope', link: 'mailto:sayhi@gockeln.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Sharing is caring!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
