mainleft:
- name: 'Start'
  url: '/index.html'
- name: 'Software'
  url: '/blog/softwaredev'
- name: 'Trading'
  url: '/blog/trading'
#  sub:
#    - name: 'Schulung'
#      url: '/priceactiontrading.html'
#    - name: 'Posts'

mainright:
- name: 'Business'
  url: '/blog/business'
- name: 'Profile'
  url: '/profil.html'
- name: 'Contact'
  url: '/kontakt.html'

footer:
- name: 'Contact'
  url: '/kontakt.html'
- name: 'Privacy'
  url: '/datenschutz.html'
- name: 'Impressum'
  url: '/impressum.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'youtube', url: 'https://www.youtube.com/channel/UCSP7m2ZTRWOc56kq1gRg7mQ'}
- {icon: 'twitter', url: 'https://twitter.com/arnegockeln'}
- {icon: 'linkedin', url: 'http://www.linkedin.com/in/arnegockeln/'}
- {icon: 'xing', url: 'https://www.xing.com/profile/Arne_Gockeln'}
- {icon: 'github', url: 'https://www.github.com/arnegockeln'}
#- {icon: 'rss-square', url: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
